import type { EditorThemeClasses } from 'lexical';

export const notebookEditorTheme: EditorThemeClasses = {
  paragraph: 'mb-2 leading-relaxed text-base',
  quote: 'border-l-4 border-muted pl-4 italic text-muted-foreground my-2',
  heading: {
    h1: 'mb-3 mt-4 text-2xl font-bold',
    h2: 'mb-2 mt-3 text-xl font-semibold',
    h3: 'mb-2 mt-2 text-lg font-semibold',
  },
  list: {
    ol: 'list-decimal ml-6 my-2',
    ul: 'list-disc ml-6 my-2',
    listitem: 'mb-1',
    listitemChecked: 'list-none ml-6 mb-1',
    listitemUnchecked: 'list-none ml-6 mb-1',
    nested: {
      listitem: 'mb-1',
    },
  },
  link: 'text-primary underline underline-offset-2 hover:text-primary/80 cursor-pointer',
  code:
    'relative block overflow-auto rounded-md bg-muted text-foreground border border-border px-3 py-16 font-mono text-sm my-2 min-h-[200px] shadow-sm',
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-blue-600',
    boolean: 'text-red-600',
    builtin: 'text-purple-600',
    cdata: 'text-gray-600',
    char: 'text-green-600',
    class: 'text-blue-600',
    'class-name': 'text-blue-600',
    comment: 'text-gray-500 italic',
    constant: 'text-red-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-600',
    entity: 'text-orange-600',
    function: 'text-blue-600',
    important: 'text-red-600',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-purple-600',
    number: 'text-orange-600',
    operator: 'text-gray-700',
    prolog: 'text-gray-600',
    property: 'text-blue-600',
    punctuation: 'text-gray-700',
    regex: 'text-orange-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-orange-600',
    tag: 'text-red-600',
    url: 'text-blue-600',
    variable: 'text-orange-600',
  },
  text: {
    bold: 'font-semibold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'rounded bg-muted px-1.5 py-0.5 font-mono text-sm',
  },
  image: 'inline-block',
  table: 'border-collapse border border-border my-4 w-full',
  tableCell: 'border border-border px-3 py-2 text-left align-top min-w-[75px]',
  tableCellHeader: 'border border-border px-3 py-2 text-left align-top font-semibold bg-muted/50',
  tableRow: '',
  tableRowStriping: 'even:bg-muted/20',
  tableSelection: 'bg-primary/10',
};
